export const actionTypes = {
  GET_POKEMONS: "GET_POKEMONS",
  GET_POKEMON_BY_ID: "GET_POKEMON_BY_ID",
  GET_POKEMON_BY_NAME: "GET_POKEMON_BY_NAME",
  GET_TYPES: "GET_TYPES",
  SET_POKEMON: "SET_POKEMON",
  GET_MY_POKEMONS: "GET_MY_POKEMONS",
};
